name: Deploy Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy hawat board
        run: |
          cd $HAWAT_BOARD_REPO_PATH
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh