name: Deploy Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy hawat board
        run: |
            echo "HAWAT_BOARD_REPO_PATH=$HAWAT_BOARD_REPO_PATH"

            if [ -d "$HAWAT_BOARD_REPO_PATH" ]; then
              echo "Directory exists"
            else
              echo "Directory DOES NOT exist"
              exit 1
            fi
            cd $HAWAT_BOARD_REPO_PATH
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh